---

# Checking first if environment is compatible with this role and if vault is already installed on nodes
- name: Ensure compatibility with this role and checking if vault is already installed
  include: asserts.yml

# Ensure requirements are in installed on nodes
- name: Ensure required OS packages are installed
  include: requirements.yml
  when: vault_install_required == true

# Installing vault on nodes only if install is required
- name: Ensure vault is installed
  include: install.yml
  when: vault_install_required == true

# Upgrade vault on nodes if the upgrade is required
- name: Upgrade vault to version {{ vault_version }}
  include: install.yml
  when: vault_upgrade_required is defined and vault_upgrade_required == true

# Configuring vault only if install is required or if auto unseal is enabled
- name: Ensure vault configuration files are defined as expected
  include: configure.yml
  when: vault_install_required == true or vault_auto_unseal == true