---
# Checking first if environment is compatible with this role
- name: Ensure compatibility with this role and checking if vault is already installed
  include: asserts.yml

# Ensure requirements are in installed 
- name: Ensure required OS packages are installed
  include: requirements.yml

# Installing vault
- name: Ensure vault is installed
  include: install.yml

# Configuring vault
- name: Ensure vault configuration files are defined as expected
  include: configure.yml
