---
### ALL ###
- name: set facts vault leader
  set_fact:
    vault_leader_hostname="{{ hostvars[item]['ansible_facts']['fqdn'] }}"
  loop: "{{ groups['vault_leader'] }}"
  when: inventory_hostname in groups['vault_leader'] and groups[your_group_name] is defined

- name: set facts shamir
  set_fact:
    shares: "-key-shares"
    threshold: "-key-threshold"
  when: vault_auto_unseal == false

- name: set fact kms
  set_fact:
    shares: "-recovery-shares"
    threshold: "-recovery-threshold"
  when: vault_auto_unseal == true
