---
- name: set facts for vault OSS
  set_fact:
    vault_pkg: "vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
    vault_shasums: "vault_{{ vault_version }}_SHA256SUMS"
    vault_zip_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/{{ vault_pkg }}"
    vault_checksum_file_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/{{ vault_shasums }}"
  when: (vault_flavor == "") or (vault_flavor == "oss")


- name: set facts for vault ENTERPRISE
  set_fact:
    vault_pkg: "vault_{{ vault_version }}+{{ vault_flavor }}_{{ vault_os }}_{{ vault_architecture }}.zip"
    vault_shasums: "vault_{{ vault_version }}+{{ vault_flavor }}_SHA256SUMS"
    vault_zip_url: "https://releases.hashicorp.com/vault/{{ vault_version }}+{{ vault_flavor }}/{{ vault_pkg }}"
    vault_checksum_file_url: "https://releases.hashicorp.com/vault/{{ vault_version }}+{{ vault_flavor }}/{{ vault_shasums }}"
  when: vault_flavor == "enterprise"


- name: set facts for vault PREMIUM
  set_fact:
    vault_bucket: "hc-enterprise-binaries"
    vault_bucket_path: "vault/{{ vault_flavor }}/{{ vault_version }}"
    vault_pkg: "vault-enterprise_{{ vault_version }}+{{ vault_flavor }}{{ vault_os }}_{{ vault_architecture }}.zip"
    vault_shasums: "vault-enterprise_{{ vault_version }}+{{ vault_flavor }}_SHA256SUMS"
    vault_zip_url: "{{ vault_bucket }}/{{ vault_bucket_path }}/{{ vault_pkg}}"
    vault_checksum_file_url: "{{ vault_bucket_path }}/{{ vault_shasums }}"
  when: vault_flavor == "prem"


- name: set facts for vault PREMIUMHSM
  set_fact:
    vault_bucket: "hc-enterprise-binaries"
    vault_bucket_path: "vault/{{ vault_flavor }}/{{ vault_version }}"
    vault_pkg: "vault-enterprise_{{ vault_version }}+{{ vault_flavor }}_{{ vault_os }}_{{ vault_architecture }}.zip"
    vault_shasums: "vault-enterprise_{{ vault_version }}+{{ vault_flavor }}_SHA256SUMS"
    vault_zip_url: "{{ vault_bucket }}/{{ vault_bucket_path }}/{{ vault_pkg}}"
    vault_checksum_file_url: "{{ vault_bucket_path }}/{{ vault_shasums }}"
  when: vault_flavor == "prem.hsm"